### ISSUE TITLE
Add a new check to flag use of `const enum` in declaration files

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/dtslint#102]
const enums break single file compilation. we should add a check to flag them and make sure no new ones are added at least.

**Comment by zspitz** [comment]
> const enums break single file compilation

@mhegazy Could you elaborate on this? Ambient `const enum`s are useful in [documenting fixed values not made available by the library's object model](https://github.com/Microsoft/TypeScript/issues/20703#issuecomment-361914358).

**Comment by andy-ms** [comment]
For reference, looks like that question was answered in Microsoft/TypeScript#20703
