### ISSUE TITLE
Feature Request: Support for TypeScript 2.8

### ISSUE THREAD

**Issue by fbartho** [Microsoft/dtslint#113]
I believe all that is necessary, is upgrading `definitelytyped-header-parser` a dependency, once that has TypeScript 2.8 support.

I have opened a PR over there for this support, and would be happy to open a PR here with that updated dependency, once it merges my PR or otherwise supports TypeScript 2.8.

https://github.com/Microsoft/definitelytyped-header-parser/pull/12

**Comment by fbartho** [comment]
Blocks:
- https://github.com/pelotom/type-zoo/pull/14

**Comment by pelotom** [comment]
@fbartho now that https://github.com/Microsoft/definitelytyped-header-parser/pull/12 is merged, maybe it's worth opening a PR to fix this, and see if it gets merged.

**Comment by fbartho** [comment]
@pelotom It looks like [dtslint/package.json](../package.json) is referring to `"definitelytyped-header-parser": "Microsoft/definitelytyped-header-parser#production",` which means all we need is a new package-lock update & deploy.

**Comment by pelotom** [comment]
@fbartho sure, but a PR to update the `package-lock.json` would take care of half of that :)

**Comment by andy-ms** [comment]
Should be supported now.
