### ISSUE TITLE
`no-redundant-jsdoc-2` triggers when no type information is present

### ISSUE THREAD

**Issue by leonard-thieu** [Microsoft/dtslint#121]
```
ERROR: 8181:9   no-redundant-jsdoc-2  JSDoc tag '@param' is redundant in TypeScript code.
```

This occurs even when `@param` is used only for documentation purposes and no type information is present.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/305612f4aca127e60a06677614312c2d3e8152aa/types/jquery/index.d.ts#L116-L117

**Comment by andy-ms** [comment]
I'm not reproducing this if I go to DefinitelyTyped, `git clean -xfd`, `npm install`, remove `"no-redundant-jsdoc-2": false,` from `types/jquery/tslint.json`, and run `npm run lint jquery`.

**Comment by leonard-thieu** [comment]
Looks like it must've been something outside of the `node_modules` directory causing it on my end. Sorry!
