### ISSUE TITLE
Question: What is the purpose of dist/immutable-nonambient.d.ts?

### ISSUE THREAD

**Issue by KSXGitHub** [Microsoft/dtslint#161]
Why does it exist?
What happen if it is removed?

**Comment by sandersn** [comment]
Sorry for my ignorance, since I'm the new owner of this project. Where is the dist/ directory? I don't see it in the source or the installed version from npm.

**Comment by KSXGitHub** [comment]
I opened this issue on the wrong repo. I'm sorry.
