### ISSUE TITLE
Version 0.4.0 on npm is missing the bin folder

### ISSUE THREAD

**Issue by ffflorian** [Microsoft/dtslint#162]
The release [0.4.0](https://www.npmjs.com/package/dtslint/v/0.4.0) is missing the `bin` folder. Included files are:

|Name | Type | Size | Last Modified|
|---|---|---|---|
| `LICENSE` | text/plain | 1.18 kB | Sat, 26 Oct 1985 08:15:00 GMT|
| `README.md` | text/markdown | 4.8 kB | Sat, 26 Oct 1985 08:15:00 GMT|
| `dt.json` | application/json | 260 B | Sat, 26 Oct 1985 08:15:00 GMT|
| `dtslint.json` | application/json | 3.77 kB | Sat, 26 Oct 1985 08:15:00 GMT|
| `package.json` | application/json | 1.13 kB | Sat, 26 Oct 1985 08:15:00 GMT|

Also see https://unpkg.com/dtslint@0.4.0/ vs https://unpkg.com/dtslint@0.3.0/.

**Comment by vfernandestoptal** [comment]
@andy-ms  @sandersn 
Hey, are you aware of this issue? Looks like something went wrong with the package publishing.
Is there a timeline for fixing this?
thanks.

**Comment by sandersn** [comment]
Should be fixed now with 0.4.1. My bash history indicates that I published 0.4.0 from the production branch but maybe I'm misreading it and I actually published from master. That's the most likely explanation for the missing `bin/` that I can think of.

**Comment by ffflorian** [comment]
Thanks @sandersn! I can confirm that the `bin/` folder is included in version 0.4.1 🙂

**Comment by vfernandestoptal** [comment]
Thanks for your fast reply!
Cheers
