### ISSUE TITLE
definitely typed issue with ReadonlyArray<T> and readonly T[]

### ISSUE THREAD

**Issue by mc0** [Microsoft/dtslint#192]
I was updating a type definition and ran into a test that began failing in a different package than the one I edited. I checked out master and ran the same tests only to find that they're failing in master. After debugging for a while, it appears like this is a bug in dtslint given the errors I'm getting.

CI:
https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/487265799 -- changes in a related package
https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/487281625 -- cosmetic changes in graphql-resolve-batch that have the error

Test:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/graphql-resolve-batch/graphql-resolve-batch-tests.ts

CLI:
```
$ npm run lint graphql-resolve-batch

> definitely-typed@0.0.3 lint /Volumes/dev/DefinitelyTyped
> dtslint types "graphql-resolve-batch"

Error: /Volumes/dev/DefinitelyTyped/types/graphql-resolve-batch/graphql-resolve-batch-tests.ts:61:5
ERROR: 61:5   expect  Expected type to be:
  ReadonlyArray<SomeTestSource>
got:
  readonly SomeTestSource[]
ERROR: 72:5   expect  Expected type to be:
  ReadonlyArray<SomeTestSource>
got:
  readonly SomeTestSource[]
ERROR: 84:5   expect  Expected type to be:
  ReadonlyArray<SomeTestSource>
got:
  readonly SomeTestSource[]
ERROR: 100:5  expect  Expected type to be:
  ReadonlyArray<SomeTestSource>
got:
  readonly SomeTestSource[]
ERROR: 116:9  expect  Expected type to be:
  ReadonlyArray<SomeTestSource>
got:
  readonly SomeTestSource[]

    at /Volumes/dev/DefinitelyTyped/node_modules/dtslint/bin/index.js:161:19
    at Generator.next (<anonymous>)
    at fulfilled (/Volumes/dev/DefinitelyTyped/node_modules/dtslint/bin/index.js:5:58)
    at <anonymous>
```

If I change a few of them to be `readonly SomeTestSource[]` then the errors start clearing from the output.

If I change each of the 5 `$ExpectType ReadonlyArray<SomeTestSource>` to be `readonly SomeTestSource[]`:
```diff
-    // $ExpectType ReadonlyArray<SomeTestSource>
+    // $ExpectType readonly SomeTestSource[]
```

Then I get this error (notice the expected/got is flipped, this feels like a heisenbug):
```
$ npm run lint graphql-resolve-batch

> definitely-typed@0.0.3 lint /Volumes/dev/DefinitelyTyped
> dtslint types "graphql-resolve-batch"

Error: /Volumes/dev/DefinitelyTyped/types/graphql-resolve-batch/graphql-resolve-batch-tests.ts:61:5
ERROR: 61:5   expect  Expected type to be:
  readonly SomeTestSource[]
got:
  ReadonlyArray<SomeTestSource>
ERROR: 72:5   expect  Expected type to be:
  readonly SomeTestSource[]
got:
  ReadonlyArray<SomeTestSource>
ERROR: 84:5   expect  Expected type to be:
  readonly SomeTestSource[]
got:
  ReadonlyArray<SomeTestSource>
ERROR: 100:5  expect  Expected type to be:
  readonly SomeTestSource[]
got:
  ReadonlyArray<SomeTestSource>
ERROR: 116:9  expect  Expected type to be:
  readonly SomeTestSource[]
got:
  ReadonlyArray<SomeTestSource>

    at /Volumes/dev/DefinitelyTyped/node_modules/dtslint/bin/index.js:161:19
    at Generator.next (<anonymous>)
    at fulfilled (/Volumes/dev/DefinitelyTyped/node_modules/dtslint/bin/index.js:5:58)
    at <anonymous>
```

Let me know if I can provide more information.

**Comment by Nayni** [comment]
I'd like to add the following findings:
* dtslint is ran against multiple versions of TypeScript (2.6 and above)
*  `$ExpectType ReadonlyArray<SomeTestSource>` works for all versioned releases but fails on typescript/next
* ` $ExpectType readonly SomeTestSource[]` works only for typescript/next but not for any of the versioned releases

Seems like a weird interplay between TypeScript and dtslint? Would love to know a solution though because this makes ReadOnlyArrays nearly impossible to lint.

**Comment by JCMais** [comment]
ping @andy-ms @sandersn @DanielRosenwasser 

This is currently blocking some PRs on DefinitelyTyped repo.

**Comment by sandersn** [comment]
Should be fixed by #195. I'll make sure it gets into the production branch so the DT PRs are unblocked.

**Comment by sandersn** [comment]
Yep, @rbuckton already merged it into the production branch.

**Comment by rbuckton** [comment]
Specifically, you can continue to use `// $ExpectType ReadonlyArray<T>` and it will work for both `ReadonlyArray<T>` and `readonly T[]` (for varying nesting levels of `ReadonlyArray`/`readonly`).
