### ISSUE TITLE
Make dtslint release as a normal npm package

### ISSUE THREAD

**Issue by Andarist** [Microsoft/dtslint#198]
Not sure what's your release schedule, but I'd love to see a new release - mainly because of #190.

If that's not possible right now - then just take your time :)

**Comment by sandersn** [comment]
Currently dtslint uses a weird release mechanism in which types-publisher installs from git's production branch, and assumes that the executable code is in `bin/`.

I need to change dtslint to be a normal npm package that ships with executable code in `bin/` and also to update types-publisher whenever I publish a new version. I'll use this issue to track that.

**Comment by sandersn** [comment]
OK, 0.4.4 is now published. I still need to change types-publisher to use the npm version.

**Comment by sandersn** [comment]
types-publisher and Definitely Typed are now using 0.4.4. I'll continue to publish that way, and remove the `push-production` task from package.json.
