### ISSUE TITLE
dtslint install fails on travis with older nodejs versions.

### ISSUE THREAD

**Issue by nivida** [Microsoft/dtslint#204]
I'm having always problems with dtslint and older versions of nodejs on travis. Dtslint works locally but sometimes it doesn't work on travis and it's not always the same error. 

For further information please check out the build on travis: 
https://travis-ci.org/ethereum/web3.js/builds/495925472

**Comment by sandersn** [comment]
Seems possible that async is working differently on older nodes since they don't have native support.

Typescript just dropped node 6 from its CI builds and I don't think dtslint has ever been tested on anything older than node 8.
