### ISSUE TITLE
always: interface name must not have an "I" prefix

### ISSUE THREAD

**Issue by vahpetr** [Microsoft/dtslint#21]
Hello
configuration "interface-name": [true, "always-prefix"] not work

**Comment by andy-ms** [comment]
This is working when I try it. I presume you have a `tslint.json` like this?
```json
{
    "extends": "dtslint/dtslint.json",
    "rules": {
        "interface-name": [true, "always-prefix"]
    }
}
```

**Comment by vahpetr** [comment]
Sorry, i forgot add tslint.json in types directory and has changed config in globall tslint.json

![image](https://cloud.githubusercontent.com/assets/10128393/24993912/dfcccaa2-2041-11e7-94ef-c23528e1e24a.png)
It's way not working.

Now dtslint work fine. Thanks

**Comment by andy-ms** [comment]
By the way, [`dtslint/dtslint.json`](https://github.com/Microsoft/dtslint/blob/master/dtslint.json) extends `tslint:latest` already, so it shouldn't be necesssary to specify both.
