### ISSUE TITLE
dtslint@0.5.6 breaks DefinitelyTyped command `npm run lint $package`

### ISSUE THREAD

**Issue by ericyhwang** [Microsoft/dtslint#219]
The [contribution instructions in DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/7d91d6eb32c29e58be79f32c502d73e4e47dcdda#edit-an-existing-package) say to run `npm run lint package-name`:

With dtslint@0.5.5, that command runs successfully. With dtslint@0.5.6, it fails with this error message:

```
$ npm run lint ____

> definitely-typed@0.0.3 lint .../DefinitelyTyped
> dtslint types "____"

.../DefinitelyTyped/node_modules/.bin/dtslint: line 1: use strict: command not found
.../DefinitelyTyped/node_modules/.bin/dtslint: line 2: syntax error near unexpected token `('
.../DefinitelyTyped/node_modules/.bin/dtslint: line 2: `var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {'
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! definitely-typed@0.0.3 lint: `dtslint types "____"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the definitely-typed@0.0.3 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Looks like it's because the `#!/usr/bin/env node` got removed, so the output `dtslint` file is interpreted as a plaintext file and not a Node JS file:
https://github.com/Microsoft/dtslint/pull/218/files#diff-f41e9d04a45c83f3b6f6e630f10117feL1

This could potentially also be fixed in DefinitelyTyped's package.json, by having it invoke the script with `node node_modules/.bin/dtslint`, though that means hard-coding a path instead of letting npm-run handle the resolution.

**Comment by alextes** [comment]
Prepending
```
#!/usr/bin/env node
```
to the binary file worked for me. The pattern seems to be followed by all other binaries in `node_modules/.bin`, perhaps this was just a minor accident?

In any case, this issue could use some ❤️ . The definitively typed repo has running this tool as one of the steps required for any PR, this step is now broken, and those people get _a lot_ of PRs 😅 .

I'll link this issue there to be helpful.

**Comment by ericyhwang** [comment]
Tagging @sandersn for issue visibility - DefinitelyTyped's `npm run lint` still errors with dtslint@0.5.7
