### ISSUE TITLE
d.ts file must have a matching npm package.

### ISSUE THREAD

**Issue by Stadly** [microsoft/dtslint#233]
I am creating typeings for [spotify-web-api-node](https://github.com/thelinmichael/spotify-web-api-node). You can see them [here](https://github.com/Stadly/DefinitelyTyped/tree/spotify-web-api-node/types/spotify-web-api-node).

When I run `npm run lint spotify-web-api-node`, I get the following error:
```
Error: /usr/src/app/types/spotify-web-api-node/index.d.ts:1:1
ERROR: 1:1      npm-naming  d.ts file must have a matching npm package.
To resolve this error, either:
1. Change the name to match an npm package.
2. Add a Definitely Typed header with the first line


    // Type definitions for non-npm package spotify-web-api-node-browser

Add -browser to the end of your name to make sure it doesn't conflict with existing npm packages.

- OR -

3. Explicitly provide dts-critic with a source file. This is not allowed for submission to Definitely Typed.
 See: https://github.com/Microsoft/dtslint/blob/master/docs/npm-naming.md
```

The file in question looks like this:
```
// Type definitions for spotify-web-api-node 4.0
// Project: https://github.com/thelinmichael/spotify-web-api-node
// Definitions by: Magnar Ovedal Myrtveit <https://github.com/Stadly>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.2

/// <reference types="spotify-api" />

declare class SpotifyWebApi {
...
}

export = SpotifyWebApi;
```

Why isn't `dtslint` able to discover that the types are for the npm package spotify-web-api-node, and how can I fix it?

**Comment by Stadly** [comment]
I was able to resolve the issue by installing `curl`, ref https://github.com/sandersn/dts-critic/issues/3.

Maybe a better error message could be implemented?

**Comment by ryuhhnn** [comment]
I got this same error and I have `curl` installed. What gives?

**Comment by CvX** [comment]
@ryuhhnn Could be the error I that https://github.com/sandersn/dts-critic/pull/7 solves.

**Comment by thekevinbrown** [comment]
I'm getting this error for this:

```
// Type definitions for @keystonejs/adapter-knex 5.1
```

But: https://www.npmjs.com/package/@keystonejs/adapter-knex

I have `curl` installed. How do I fix it?

**Comment by gabritto** [comment]
The new version of [dts-critic](https://www.npmjs.com/package/dts-critic/v/3.0.0) should no longer have those issues. It doesn't use `curl` anymore and should be more resilient when attempts to find an existing npm package fail.
