### ISSUE TITLE
[npm-naming] ... but the source does not mention 'default' anywhere.

### ISSUE THREAD

**Issue by PopGoesTheWza** [microsoft/dtslint#255]
I am updating a types definition for DT. When running the linter I get the error message:

```
ERROR: 540:1    npm-naming               The types for xxxxxxxx specify 'export default' but the source does not mention 'default' anywhere.
```

I search for a solution with google and SO but without success (a workaround seems to use `export = xxxx` instead)

Can this cryptic error message be clarified? (`npm-naming` errors in general are not well documented.)

**Comment by garyking** [comment]
The error links to [here](https://github.com/Microsoft/dtslint/blob/master/docs/npm-naming.md) which doesn't even exist. So I agree, the error message is not helpful at all.

**Comment by PopGoesTheWza** [comment]
So... the error message originates within the `dts-critic` package by @sandersn which is called by the `npm-naming` rule.

This package checks declarations from the `.d.ts` files with the source code... which is not available in the context of producing a DT package.

I am now unsure what (if any) is the difference between `export default <token>` and `export = <token>`

**Comment by sandersn** [comment]
The dtslint link is auto-generated. I should probably add a page there.

The fix is not always `export =` but almost always. I can update dts-critic. What do you think of 

"The most common way to resolve this error is to use 'export =' insead of 'export default'"

**Comment by PopGoesTheWza** [comment]
Sure.

Still I wonder about the reason for this test. Do the two syntax impact the performance of the .d.ts? Or what an import/require would retrieve?

Also if dts-critic needs to access the source .ts/.js to scan for exports, instructions to setup would be nice.

And finally, since I ran into this error while writing .d.ts for an old school “export a single IIFE” which is rather common, is the “export =“ the recommended syntax?

Thanks in advance,

**Comment by sandersn** [comment]
`export default` can only be used to import a commonjs `module.exports =` when you have esModuleInterop turned on, which not everybody does.

You can manually pass a source path to dts-critic. Without that, it tries to download the source from unpkg. dtslint doesn't have access to a source path so it uses unpkg.

If you wrote

```js
module.exports = (function () {
})()
```

then you do need `export =`

**Comment by PopGoesTheWza** [comment]
Add this to the page you're going to add please :)

**Comment by PopGoesTheWza** [comment]
@sandersn thanks
