### ISSUE TITLE
TS versions for parsing source and linting rules differ

### ISSUE THREAD

**Issue by Maxim-Mazurok** [microsoft/dtslint#281]
It all started here, when our CI for linting type definitions for Google APIs started failing after dtslint update: https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/101

First, I thought that something is wrong with TS itself, so I opened issue there with my investigation details: https://github.com/microsoft/TypeScript/issues/37551

But then I found out that `dtslint` uses different TS versions for parsing source and for applying linting rules (see https://github.com/microsoft/TypeScript/issues/37551#issuecomment-603232066).

When parsing source, dtslint uses `Linter.createProgram(tsconfigPath)` which resolves to project's TS. But then in rules, it requires internal (bundled) TS: `import * as ts from "typescript";`. Which results in unpredicted behavior, because version might not match at all.
In my case, `SyntaxKind.VoidKeyword` and other `SyntaxKind.*`s values were changed because of https://github.com/microsoft/TypeScript/pull/35998 PR to TS.

I think we should either use projects TS, or use bundled TS version for both tasks. I'll be happy to investigate more and open PR with this change. Let me know what you think, thanks!

**Comment by IvanGoncharov** [comment]
We experience the same issue on `graphql-js` and I left a detailed comment here: https://github.com/microsoft/dtslint/pull/292#issuecomment-635255700

**Comment by sandersn** [comment]
tslint has typescript as a peer dependency, so it should pick up whatever is installed. So it actually looks like the fault of dtslint's dependencies `dts-critic` and `@definitelytyped/definitions-parser`, which both depend on older versions of Typescript. They should both have typescript as a peer dependency too.

**Comment by IvanGoncharov** [comment]
@sandersn Thanks for trying to address this issue 👍 
In `graphql-js` we still experience the same issue even after we updated to `3.6.9`:
![image](https://user-images.githubusercontent.com/8336157/83295128-2819e080-a1f7-11ea-91bf-8660078f85bc.png)

We also use `eslint-typescript` so we a forced to have `typescript` as a direct dependency and `tslint` use it instead of `dtslint` version.
Not sure if it's possible but ideally `typescript` should either `peerDependency` or `devDependency` of `dtslint`.

**Comment by Maxim-Mazurok** [comment]
@IvanGoncharov try this PR locally: https://github.com/microsoft/dtslint/pull/295 it worked for me like a charm :)
It does exactly what you suggested.
