### ISSUE TITLE
Object.entries is not a function

### ISSUE THREAD

**Issue by AJamesPhillips** [Microsoft/dtslint#29]
Perhaps dtslint only works on node 7.x ?

    DefinitelyTyped$ node --version
    v6.10.2  # latest LTS version
    DefinitelyTyped$ npm --version
    4.2.0
    DefinitelyTyped$ git log -n 1
    commit 43408431520aaedbb7520015d3fdba816f0f6fc6
    ...
    DefinitelyTyped$ npm install
    DefinitelyTyped$ grep '"version"' node_modules/dtslint/package.json
      "version": "0.1.1",
    DefinitelyTyped$ echo '{ "extends": "dtslint/dt.json" }' > types/boom/tslint.json
    DefinitelyTyped$ cat types/boom/tslint.json
    { "extends": "dtslint/dt.json" }
    DefinitelyTyped$ npm run lint boom

    > definitely-typed@0.0.1 lint /abc/DefinitelyTyped
    > dtslint types "boom"

    Object.entries is not a function

    npm ERR! Darwin 15.6.0
    npm ERR! argv "/usr/local/Cellar/node@6/6.10.2/bin/node" "/usr/local/bin/npm" "run" "lint" "boom"
    npm ERR! node v6.10.2
    npm ERR! npm  v4.2.0
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! definitely-typed@0.0.1 lint: `dtslint types "boom"`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the definitely-typed@0.0.1 lint script 'dtslint types "boom"'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the definitely-typed package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     dtslint types "boom"
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs definitely-typed
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls definitely-typed
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/bcd/.npm/_logs/2017-04-21T14_48_46_581Z-debug.log

    DefinitelyTyped$ cat /Users/bcd/.npm/_logs/2017-04-21T14_48_46_581Z-debug.log
    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/local/Cellar/node@6/6.10.2/bin/node',
    1 verbose cli   '/usr/local/bin/npm',
    1 verbose cli   'run',
    1 verbose cli   'lint',
    1 verbose cli   'boom' ]
    2 info using npm@4.2.0
    3 info using node@v6.10.2
    4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
    5 info lifecycle definitely-typed@0.0.1~prelint: definitely-typed@0.0.1
    6 silly lifecycle definitely-typed@0.0.1~prelint: no script for prelint, continuing
    7 info lifecycle definitely-typed@0.0.1~lint: definitely-typed@0.0.1
    8 verbose lifecycle definitely-typed@0.0.1~lint: unsafe-perm in lifecycle true
    9 verbose lifecycle definitely-typed@0.0.1~lint: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/abc/DefinitelyTyped/node_modules/.bin:/usr/local/bin:/usr/local/opt/node@6/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/heroku/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/Users/bcd/.rvm/bin:/Users/bcd/bin:/usr/local/opt/go/libexec/bin
    10 verbose lifecycle definitely-typed@0.0.1~lint: CWD: /abc/DefinitelyTyped
    11 silly lifecycle definitely-typed@0.0.1~lint: Args: [ '-c', 'dtslint types "boom"' ]
    12 silly lifecycle definitely-typed@0.0.1~lint: Returned: code: 1  signal: null
    13 info lifecycle definitely-typed@0.0.1~lint: Failed to exec lint script
    14 verbose stack Error: definitely-typed@0.0.1 lint: `dtslint types "boom"`
    14 verbose stack Exit status 1
    14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
    14 verbose stack     at emitTwo (events.js:106:13)
    14 verbose stack     at EventEmitter.emit (events.js:191:7)
    14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
    14 verbose stack     at emitTwo (events.js:106:13)
    14 verbose stack     at ChildProcess.emit (events.js:191:7)
    14 verbose stack     at maybeClose (internal/child_process.js:886:16)
    14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
    15 verbose pkgid definitely-typed@0.0.1
    16 verbose cwd /abc/DefinitelyTyped
    17 error Darwin 15.6.0
    18 error argv "/usr/local/Cellar/node@6/6.10.2/bin/node" "/usr/local/bin/npm" "run" "lint" "boom"
    19 error node v6.10.2
    20 error npm  v4.2.0
    21 error code ELIFECYCLE
    22 error errno 1
    23 error definitely-typed@0.0.1 lint: `dtslint types "boom"`
    23 error Exit status 1
    24 error Failed at the definitely-typed@0.0.1 lint script 'dtslint types "boom"'.
    24 error Make sure you have the latest version of node.js and npm installed.
    24 error If you do, this is most likely a problem with the definitely-typed package,
    24 error not with npm itself.
    24 error Tell the author that this fails on your system:
    24 error     dtslint types "boom"
    24 error You can get information on how to open an issue for this project with:
    24 error     npm bugs definitely-typed
    24 error Or if that isn't available, you can get their info via:
    24 error     npm owner ls definitely-typed
    24 error There is likely additional logging output above.
    25 verbose exit [ 1, true ]

**Comment by andy-ms** [comment]
This is made explicit in the [`package.json`](https://github.com/Microsoft/dtslint/blob/1fb637e38a6f7f91289a64f5a5992e4b7e6218f2/package.json#L41).

**Comment by AJamesPhillips** [comment]
Ah ok.  Thanks.  I will set up a virtual env for node 7.x to run this through as I need to stay on 6.x to stay broadly sane.  Thanks.
