### ISSUE TITLE
Add support for typescript 2.3

### ISSUE THREAD

**Issue by CaselIT** [Microsoft/dtslint#31]
At the moment dtslint does not support the default generic types introduced in typescript 2.3

This causes pr builds to fail on DefinitelyTyped
Example:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16196
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16198

edit: this is not the the only responsible for build fails on DT, but at the moment it fails when testing locally a package with default generic types

**Comment by andy-ms** [comment]
We generally wait until a month after a release before changing any packages on DefinitelyTyped. This gives people time to upgrade to the new TypeScript version before packages start requiring it.
Based on that we should enable ts2.3 support on May 27.

**Comment by CaselIT** [comment]
Thanks forum the info @andy-ms
I was not aware of this practice.
Do you prefer if I close che PR on DT and reopen them in a month time, or should I just leave them open?

**Comment by andy-ms** [comment]
It's up to you.

**Comment by CaselIT** [comment]
Ok, I'll leave them open and reference this issue.

Thanks

**Comment by DanielRosenwasser** [comment]
Do we have to have this rule in place across all packages instead of just existing ones? Seems like if a declaration file doesn't exist, there's no reason to keep the restriction in place.

**Comment by andy-ms** [comment]
That would be nice but the way dtslint is designed, it doesn't distinguish between new/changed packages. I guess we could edit types-publisher to just look for the string `// TypeScript Version: 2.3` on changed packages only, and have failures through that instead of dtslint.

**Comment by DanielRosenwasser** [comment]
Yes, dtslint just failing on the header is likely confusing to new users.

**Comment by CaselIT** [comment]
Shouldn't this waiting period be implemented in the type publisher?
According to the header it could only update the definition after the month, or alternatively it could publish the updated definition on a `next` tag in npm and update the `latest` tag only after a month.
