### ISSUE TITLE
installer.js: tslint dependency as dependency, not devDependency in package.json

### ISSUE THREAD

**Issue by stevegeek** [Microsoft/dtslint#36]
While trying to run `dtslint` on some typings I got the following error:

```DefinitelyTyped stephen$ ./node_modules/dtslint/bin/index.js dot
.../DefinitelyTyped/node_modules/dtslint/bin/installer.js:79
    throw new Error("Missing tslint version.");
    ^
Error: Missing tslint version.
    at Object.<anonymous> (.../DefinitelyTyped/node_modules/dtslint/bin/installer.js:79:11)
```

On this line https://github.com/Microsoft/dtslint/blob/master/src/installer.ts#L65 the app is expecting `tslint` as a `devDependency` in `package.json` however https://github.com/Microsoft/dtslint/blob/master/package.json#L30 tslint is specified as a `dependency`

**Comment by andy-ms** [comment]
Fixed by 9cc69ec.
