### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by CatsMiaow** [Microsoft/dtslint#5]
![20170306_185711](https://cloud.githubusercontent.com/assets/1300172/23605119/c63f4c2e-029e-11e7-8bee-04e0e9f1b30a.png)

http://registry.npmjs.org/dtslint
The result is {}.

**Comment by umidbekkarimov** [comment]
Seems like it's not published to [npm](https://www.npmjs.com/search?q=dtslint).

**Comment by andy-ms** [comment]
Sorry for the delay. It's published now.
