### ISSUE TITLE
Best way to include as a dependency?

### ISSUE THREAD

**Issue by lazerwalker** [Microsoft/dtslint#71]
Hi!

I'm using dtslint in a project that uses TS 2.4 (I've got a JS lib with a TS type definition file, and dtslint as a dev dependency to run on CI).

The latest npm release of dtslint (`0.1.2`) seems pretty old, and chokes if your type definition file specifies a TypeScript version > 2.3. I was able to get around this by pointing my package.json directly to this repo's `production` branch.

What's the desired way for folks to include this as a dependency? If it's npm, I'd love to see a more updated version published to the registry. If it's to use the `production` branch, a few sentences added to the README would probably go a long way — I'm happy to open a PR.

Without that much context on the project, I'm curious if someone more familiar with it has thoughts about how best to proceed.

Thanks!

**Comment by corydeppen** [comment]
It would be helpful to hear from the dtslint team on this and other open issues surrounding the version of TS being used and whether we can expect to see a release in the near future that resolves these issues.

**Comment by andy-ms** [comment]
Should be fixed with the 0.2 release.

**Comment by lazerwalker** [comment]
Besides bumping a new release (which is very much appreciated!) is there a plan going forward to more proactively cut new npm releases?
