### ISSUE TITLE
Error: Expected `"strictFunctionTypes": true` or `"strictFunctionTypes": false`

### ISSUE THREAD

**Issue by cdeutsch** [Microsoft/dtslint#81]
In #80 `strictFunctionTypes` was made required.

Not a single tsconfig.json in DefinitelyTyped has this specified, so you get this when running `npm run lint <type name>` for DefinitelyTyped definitions:

> Error: Expected `"strictFunctionTypes": true` or `"strictFunctionTypes": false`

Not sure if this is intended or not, otherwise I'd make a PR

/cc @andy-ms

**Comment by andy-ms** [comment]
DefinitelyTyped/DefinitelyTyped#20373 enabled this on DefinitelyTyped.

**Comment by cdeutsch** [comment]
Ah! Ok. 

Pulling from master fixed it.

Thanks for the quick reply
